### ISSUE TITLE
Jurryt en Nout doen niet zo veel.. :(

### ISSUE THREAD

**Issue by maxverbeek** [Magister-Android/Magister-Android#4]
Wat kunnen we hier aan doen?

**Comment by SibrenTalens** [comment]
We zouden ze kunnen kicken uit het groepje, maar dat vind ik persoonlijk best wel een klein beetje zielig. Daarnaast is [reward beter dan punishment](https://www.psychologytoday.com/blog/family-affair/200809/rewards-are-better-punishment-here-s-why) dus als we gewoon een politie virus op hun Windows PC's loslaten en die pas weghalen als ze wat gaan doen, lijkt me dat toch wel een reward.

**Comment by SibrenTalens** [comment]
Ik close hem maar want dan staat er dat we issues ook daadwerkelijk fixen maar ze doen nog steeds niks lol
